### ISSUE TITLE
Cannot build from source and run plugin on Idea 14

### ISSUE THREAD

**Issue by koroandr** [esteinberg/plantuml4idea#105]
I tried to build this plugin from source (wanted to add some features).

1. Clone repository, check out master.
2. Run grammar-gen.sh
3. Run "Generate" on PlantUml.bnf
4. Create Run/Debug configuration and click "debug"

Got this exception:

```
java.lang.Throwable: Extension class org.plantuml.idea.lang.PlantUmlTypeFactory does not implement class com.intellij.openapi.fileTypes.FileTypeFactory
	at com.intellij.openapi.extensions.Extensions$SimpleLogProvider.error(Extensions.java:221)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:150)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:247)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:195)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:110)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:96)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:166)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:270)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
	at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:549)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:609)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:358)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:727)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.awt.EventQueue$3.run(EventQueue.java:686)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:697)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

Could anyone help?

**Comment by krasa** [comment]
At this point, you would be better off doing it on 1.x branch.

**Comment by koroandr** [comment]
On 1.x there is no "tools" folder. Is there any reason for that? Or it appeared directly in master?

**Comment by krasa** [comment]
Master contains new language support, but it is not finished yet, I am not sure if anyone continues to develop it... 
1.x does not need any generated classes, you just checkout it and run it.

**Comment by koroandr** [comment]
Thank you a lot! That helped.

Probably you should put this in master README.md file, it's not obvious at all :)

**Comment by krasa** [comment]
Good point. Will do.
