### ISSUE TITLE
"Note on link" IllegalArgumentException

### ISSUE THREAD

**Issue by ar3b** [esteinberg/plantuml4idea#114]
# Input:
> app -up> api
> note on link
>     Some note here
> end note

[full.puml.txt](https://github.com/esteinberg/plantuml4idea/files/55097/test.txt)

# Exception:
class net.sourceforge.plantuml.command.regex.RegexConcat     note on link
java.lang.IllegalArgumentException: class net.sourceforge.plantuml.command.regex.RegexConcat     note on link
	at net.sourceforge.plantuml.command.regex.RegexComposed.matcher(RegexComposed.java:77)
	at net.sourceforge.plantuml.command.note.FactoryNoteOnLinkCommand$1.executeNow(FactoryNoteOnLinkCommand.java:87)
	at net.sourceforge.plantuml.command.note.FactoryNoteOnLinkCommand$1.executeNow(FactoryNoteOnLinkCommand.java:75)
	at net.sourceforge.plantuml.command.CommandMultilines2.execute(CommandMultilines2.java:88)
	at net.sourceforge.plantuml.command.UmlDiagramFactory.manageMultiline(UmlDiagramFactory.java:184)
	at net.sourceforge.plantuml.command.UmlDiagramFactory.executeOneLine(UmlDiagramFactory.java:128)
	at net.sourceforge.plantuml.command.UmlDiagramFactory.createSystem(UmlDiagramFactory.java:103)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:99)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:105)
	at org.plantuml.idea.plantuml.PlantUml.doRender(PlantUml.java:135)
	at org.plantuml.idea.plantuml.PlantUml.render(PlantUml.java:65)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.renderWithBaseDir(PlantUmlToolWindow.java:214)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.access$1000(PlantUmlToolWindow.java:42)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$RenderWithBaseDirRunnable.run(PlantUmlToolWindow.java:202)
	at org.plantuml.idea.util.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by krasa** [comment]
It should work now.
