### ISSUE TITLE
IntelliJ does not display the plantUML diagram

### ISSUE THREAD

**Issue by mousashaya** [esteinberg/plantuml4idea#123]
Diagram not showing up in plantuml page in IntelliJ. I am running in Windows 7 Enterprise and I have installed Graphviz and added graphviz to path. I installed the plantUML plugin into ItelliJ. What else do I need to do?

I am using the default example:
@startuml

package "Some Group" {
HTTP - [First Component]
[Another Component]
}

package "Other Groups" {
FTP - [Second Component]

[First Component] --> FTP
}

@enduml

**Comment by krasa** [comment]
Anything in the log?

**Comment by mousashaya** [comment]
Thanks for pointing that out. Yes there are exceptions:
2016-06-02 15:08:11,827 [  12566]  ERROR - til.concurrency.QueueProcessor - net/sourceforge/plantuml/Scale 
java.lang.NoClassDefFoundError: net/sourceforge/plantuml/Scale
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:46)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:31)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:282)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.plantuml.Scale PluginClassLoader[PlantUML integration, 1.9.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

**Comment by mousashaya** [comment]
Here is preamble I missed:
2016-06-02 15:08:09,666 [  10405]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2016.1.2  Build #IU-145.972.3 
2016-06-02 15:08:09,666 [  10405]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_92 
2016-06-02 15:08:09,667 [  10406]  ERROR - pplication.impl.LaterInvocator - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-06-02 15:08:09,667 [  10406]  ERROR - pplication.impl.LaterInvocator - Vendor: Oracle Corporation 
2016-06-02 15:08:09,667 [  10406]  ERROR - pplication.impl.LaterInvocator - OS: Windows 7 
2016-06-02 15:08:09,667 [  10406]  ERROR - pplication.impl.LaterInvocator - Last Action:  
2016-06-02 15:08:09,948 [  10687]   INFO - ateSettings.impl.UpdateChecker - Connection failed (java.security.cert.CertificateException: No name matching www.jetbrains.com found). Please check network connection and try again. 
2016-06-02 15:08:10,076 [  10815]   INFO - ution.rmi.RemoteProcessSupport - Port/ID: 37175/Maven30ServerImpl8ee79572 
2016-06-02 15:08:11,827 [  12566]  ERROR - til.concurrency.QueueProcessor - net/sourceforge/plantuml/Scale 
java.lang.NoClassDefFoundError: net/sourceforge/plantuml/Scale
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:46)

**Comment by krasa** [comment]
Looks like the plantuml library is missing, try reinstalling. If you are installing downloaded file manually, make sure to select the whole zip file.

**Comment by mousashaya** [comment]
All set thanks for your help!
