### ISSUE TITLE
IntelliJIDEA 2016.1.3

### ISSUE THREAD

**Issue by sbhanderi** [esteinberg/plantuml4idea#128]
Any ideas when this plugin will work with the latest version ?

**Comment by krasa** [comment]
Why do you think it does not work?

**Comment by sbhanderi** [comment]
2 issues occur.
When plantuml integration plugin is enabled, and graphiz points to the correct dot file, when I open up the idea, I get the exception as follows :+1: 
Plugin 'PlantUML integration' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:520)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:511)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:491)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:484)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1263)
    at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:31)
    at com.intellij.openapi.application.Preloader$2$1.run(Preloader.java:78)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.Preloader$2.run(Preloader.java:74)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:484)
    ... 17 more
Caused by: java.lang.NoClassDefFoundError: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils
    at org.plantuml.idea.lang.settings.PlantUmlSettings.applyState(PlantUmlSettings.java:126)
    at org.plantuml.idea.lang.settings.PlantUmlSettings.loadState(PlantUmlSettings.java:109)
    at org.plantuml.idea.lang.settings.PlantUmlSettings.loadState(PlantUmlSettings.java:19)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:96)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
    at org.plantuml.idea.lang.settings.PlantUmlSettings.getInstance(PlantUmlSettings.java:34)
    at org.plantuml.idea.action.ReloadNowAction.<init>(ReloadNowAction.java:22)
    ... 22 more
Caused by: java.lang.ClassNotFoundException: net.sourceforge.plantuml.cucadiagram.dot.GraphvizUtils PluginClassLoader[PlantUML integration, 2.2.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 35 more

**Comment by sbhanderi** [comment]
I don't see the same error in 13.1.7

**Comment by sbhanderi** [comment]
I just deleted then reinstalled the whole IntelliIDEA application.
Seems to be OK now.
I did not install the "PlantUML Syntax Check" plugin this time, which I did previously.
So I can close this now.
