### ISSUE TITLE
Diagram display crashes

### ISSUE THREAD

**Issue by eduardotomassi** [esteinberg/plantuml4idea#132]
**When i open the diagram it crashes and does not display it.**
IntelliJ IDEA 2016.2.2
Build #IC-162.1628.40, built on August 16, 2016
JRE: 1.8.0_102-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

This is the stack trace:

Exception occurred rendering org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand@5243ca59[reason=SOURCE_PAGE_ZOOM,sourceFilePath=*******.puml,selectedDir=impl,page=-1,zoom=100,cachedItem=<null>,version=1]: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils
java.lang.NoClassDefFoundError: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils
	at org.plantuml.idea.lang.settings.PlantUmlSettings.applyPlantumlOptions(PlantUmlSettings.java:135)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:44)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:62)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.plantuml.cucadiagram.dot.GraphvizUtils PluginClassLoader[PlantUML integration, 2.3.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

java.lang.NoClassDefFoundError: net/sourceforge/plantuml/FileSystem
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.checkSyntax(PlantUmlExternalAnnotator.java:120)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.annotateSyntaxErrors(PlantUmlExternalAnnotator.java:93)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:60)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.NoClassDefFoundError: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils
	at org.plantuml.idea.lang.settings.PlantUmlSettings.applyPlantumlOptions(PlantUmlSettings.java:135)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:44)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:62)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by krasa** [comment]
reinstall the plugin
