### ISSUE TITLE
plantuml display crashes with NoClassDefFoundError

### ISSUE THREAD

**Issue by RoopeshMajeti** [esteinberg/plantuml4idea#135]
i have installed PlantUML plugin into intellij ( tried with version 2.3.1 and 2.3.0 from https://plugins.jetbrains.com/plugin/7017 ). But when tried to bring up the diagrametric version of the uml file, it is crashing with the below error : 

Exception occurred rendering org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand@1e9316eb[reason=SOURCE_PAGE_ZOOM,sourceFilePath=/Users/majetir/code/csp/csp-java-api-documentvault/src/main/DocumentRequest.puml,selectedDir=main,page=-1,zoom=100,cachedItem=<null>,version=20]: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils
java.lang.NoClassDefFoundError: net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils
	at org.plantuml.idea.lang.settings.PlantUmlSettings.applyPlantumlOptions(PlantUmlSettings.java:135)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:44)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:62)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by krasa** [comment]
https://github.com/esteinberg/plantuml4idea/issues?utf8=%E2%9C%93&q=NoClassDefFoundError

**Comment by OllieJUK** [comment]
I made the mistake of extracting the zip file and choosing the plantuml4idea.jar which succeeded to install as a plugin but gave this error when opening files. Installing the plugin by selecting the whole zip file works.
