### ISSUE TITLE
Doesn't seem to work with AndroidStudio

### ISSUE THREAD

**Issue by VictorSago** [esteinberg/plantuml4idea#149]
I'm running AndroidStudio 2.3 on Ubuntu 14.04. Graphviz version 2.36 is installed and working, but PlantUML plugin crashes with NullPointerException as soon as I try to use it.

**Comment by krasa** [comment]
stacktrace?

**Comment by VictorSago** [comment]
Here's an excerpt from file `idea.log`:
2017-03-29 18:59:15,548 [ 131119]  ERROR - pplication.impl.LaterInvocator - null 
java.lang.NullPointerException
	at org.plantuml.idea.toolwindow.Usage.<init>(Usage.java:32)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.setupUI(PlantUmlToolWindow.java:104)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.<init>(PlantUmlToolWindow.java:73)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindowFactory.createToolWindowContent(PlantUmlToolWindowFactory.java:23)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:568)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$9.run(ToolWindowManagerImpl.java:550)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
Thanks, I will release it soon.

**Comment by aadrian** [comment]
> I will release it soon.

@krasa any chance merging PR https://github.com/esteinberg/plantuml4idea/pull/148 too before releasing?
