### ISSUE TITLE
NPE in PlantUmlExternalAnnotator.java

### ISSUE THREAD

**Issue by zbstof** [esteinberg/plantuml4idea#164]
I get this when I don't even open any plantuml files:
```
java.lang.NullPointerException
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.checkSyntax(PlantUmlExternalAnnotator.java:115)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.annotateSyntaxErrors(PlantUmlExternalAnnotator.java:93)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:60)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by krasa** [comment]
and what kind of file was opened?
