### ISSUE TITLE
Plugin throws an exception when plantuml can't load an image from a URL in an include file.

### ISSUE THREAD

**Issue by mattbishop** [esteinberg/plantuml4idea#220]
Here is the stack trace:

```
Exception occurred rendering org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand@5d8c70bc[reason=REFRESH,sourceFilePath=/Users/mbishop/Sides/Level3-REST/site/doc/patterns/process/relations.puml,selectedDir=process,page=-1,zoom=100,cachedItem=<null>,version=1]

java.lang.RuntimeException: @startuml
!include ../../copyright.iuml

title Process Pattern

rectangle "<&info> | <&aperture> Process" as Process
rectangle "<&question-mark> Activity" as Activity

Process 0-->> "1..N" Activity: "activity, blocked-by"
Activity 0-->> Process: "process"
Activity 0-->> Activity: "blocks, blocked-by"

@enduml; baseDir=/Users/mbishop/Sides/Level3-REST/site/doc/patterns/process
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:42)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:62)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.plantuml.idea.rendering.RenderingCancelledException: java.lang.InterruptedException
	at org.plantuml.idea.plantuml.PlantUmlIncludes.saveModifiedFiles(PlantUmlIncludes.java:64)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:32)
	... 8 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:81)
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:73)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:174)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.saveModifiedFiles(PlantUmlIncludes.java:51)
	... 9 more
```

**Comment by krasa** [comment]
Here is a fixed version if you need it now:
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/3122510/plantuml4idea.zip)

**Comment by ftok06** [comment]
thanks alot. i spend my two days to solve the problem. plantuml didn't show graph. Thanks again.
