### ISSUE TITLE
IDE error upon startup after recent upgrade

### ISSUE THREAD

**Issue by jbprek** [esteinberg/plantuml4idea#222]
IDE error on startup after loading project with PlantUML diagrams
==========================================

This occurs on startup of a project containning PlantUML diagrams only:

IntelliJ IDEA 2019.1.2 (Ultimate Edition)
Build #IU-191.7141.44, built on May 7, 2019

JRE: 1.8.0_202-release-1483-b49 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 7 6.1

PlantUML Integration version 2.15.1

The details of the message without the puml code.

Exception occurred rendering org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand@23d75e[reason=REFRESH,sourceFilePath=D:/AIBProjects/low-level-design/tsys_endpoint_activity_diagram.puml,selectedDir=low-level-design,page=-1,zoom=100,cachedItem=<null>,version=1]

java.lang.RuntimeException: @startuml

<OMMITED>

@enduml; baseDir=
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:42)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:62)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.plantuml.idea.rendering.RenderingCancelledException: java.lang.InterruptedException
	at org.plantuml.idea.plantuml.PlantUmlIncludes.saveModifiedFiles(PlantUmlIncludes.java:64)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.commitIncludes(PlantUmlIncludes.java:32)
	... 8 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:81)
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:73)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:174)
	at org.plantuml.idea.plantuml.PlantUmlIncludes.saveModifiedFiles(PlantUmlIncludes.java:51)
	... 9 more

**Comment by krasa** [comment]
Fixed by #220
