### ISSUE TITLE
Failed to render image

### ISSUE THREAD

**Issue by saabeilin** [esteinberg/plantuml4idea#235]
That's the stacktrace I get both in latest PyCharm Pro and Idea Ultimate (2019.2.x), while works seamlessly in Idea EAP 2019.3

```
java.lang.NoSuchMethodError: 'boolean com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi.canDecodeAs(java.lang.Object, int)'
	at com.twelvemonkeys.imageio.plugins.tiff.BigTIFFImageReaderSpi.canDecodeInput(BigTIFFImageReaderSpi.java:58)
	at java.desktop/javax.imageio.ImageIO$CanDecodeInputFilter.filter(ImageIO.java:571)
	at java.desktop/javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:876)
	at java.desktop/javax.imageio.spi.FilterIterator.next(ServiceRegistry.java:894)
	at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:531)
	at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1463)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
	at org.plantuml.idea.util.UIUtils.getBufferedImage(UIUtils.java:41)
	at org.plantuml.idea.rendering.ImageItem.<init>(ImageItem.java:73)
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.generateImageItem(PlantUmlNormalRenderer.java:235)
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.normalRendering(PlantUmlNormalRenderer.java:172)
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.doRender(PlantUmlNormalRenderer.java:132)
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.render(PlantUmlRendererUtil.java:73)
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:66)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:122)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by krasa** [comment]
check this https://youtrack.jetbrains.net/issue/UP-10334

**Comment by saabeilin** [comment]
Thanks a lot @krasa - removing the old libraries actually solved the issue!
