### ISSUE TITLE
java.lang.IllegalArgumentException on diagrams with empty `StereotypeFontSize 0` element

### ISSUE THREAD

**Issue by matschaffer** [esteinberg/plantuml4idea#261]
Apologies for the broad bug report, but I'm having an odd issue with _just_ the IntelliJ plugin that I can't reproduce even by calling ` java -jar ~/Library/Application\ Support/JetBrains/IntelliJIdea2020.2/plugins/plantuml4idea/lib/plantuml.1.2020.9.jar -t png ...`

Here's the stacktrace from the intellij log:

```
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - java.lang.IllegalArgumentException
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.Dimension2DDouble.<init>(Dimension2DDouble.java:49)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.FileFormat.getJavaDimension(FileFormat.java:128)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.FileFormat.access$000(FileFormat.java:61)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.FileFormat$1.calculateDimension(FileFormat.java:118)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.creole.atom.AtomText.calculateDimension(AtomText.java:192)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.creole.Sea.add(Sea.java:57)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.creole.SheetBlock1.initMap(SheetBlock1.java:116)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.creole.SheetBlock1.calculateDimension(SheetBlock1.java:158)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.creole.SheetBlock2.calculateDimension(SheetBlock2.java:90)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.graphic.USymbolRect$1.calculateDimension(USymbolRect.java:94)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.image.EntityImageDescription.calculateDimension(EntityImageDescription.java:212)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.Node.<init>(Node.java:98)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.Bibliotekon.createNode(Bibliotekon.java:63)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntity(GeneralImageBuilder.java:517)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.GeneralImageBuilder.printGroups(GeneralImageBuilder.java:576)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:374)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:112)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:77)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:651)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:201)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:158)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.generateImageItem(PlantUmlNormalRenderer.java:219)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.incrementalRendering(PlantUmlNormalRenderer.java:163)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.doRender(PlantUmlNormalRenderer.java:135)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at org.plantuml.idea.rendering.PlantUmlRendererUtil.render(PlantUmlRendererUtil.java:74)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:71)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:122)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
2020-08-24 15:39:14,248 [1096247]   INFO -                         STDERR - 	at java.base/java.lang.Thread.run(Thread.java:834)
```

And the diagram

```
@startuml

!pragma revision 1
!pragma teoz true

skinparam maxMessageSize 120
skinparam pathHoverColor red
skinparam svgLinkTarget _parent
skinparam ArrowThickness 2
scale 0.9

!define includes ./includes

!include includes/C4.puml
!include includes/C4_Container.puml

node pingdom

Boundary(ess, "ESS") {
}

@enduml
```

C4 is from https://github.com/RicardoNiepel/C4-PlantUML (58b5da5).

If I fill in the `Boundary`, the diagram works fine. It also works fine via the CLI.

Here's the generated error as well. Looks like it might have something to do dimension calculation.

![diagram-error](https://user-images.githubusercontent.com/690/91012307-da0f5000-e620-11ea-99dd-dd5b596987fb.png)

**Comment by krasa** [comment]
Works fine for me, try a new version.

**Comment by matschaffer** [comment]
Still happening on `2.27.0` which I updated to today. 
![ingest_global](https://user-images.githubusercontent.com/690/98458947-2f4b0e80-21d9-11eb-9a34-b6cdd43daa9f.png)

Does the plugin run plantuml from the same JVM as intellij? If so that'd be 

```
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Licensed to Mat Schaffer
Subscription is active until January 15, 2021
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: PlantUML integration, com.intellij.nativeDebug, com.intellij.plugins.watcher, com.tabnine.TabNine, org.intellij.plugins.hcl, name.kropp.intellij.makefile, org.toml.lang, intellij.prettierJS, org.jetbrains.kotlin, org.intellij.scala, com.intellij.lang.jsgraphql, org.jetbrains.plugins.ruby, Pythonid, org.jetbrains.plugins.go, org.rust.lang
```

`java` on my CLI path is:

```
❯ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

So definitely not the same. Will see if I can invoke intellij's java directly.

**Comment by matschaffer** [comment]
Found it. Same error if I invoke plantuml from the `java` I found in the intellij app bundle.

```
❯ /Applications/IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment JBR-11.0.8.10-944.34-jcef (build 11.0.8+10-b944.34)
OpenJDK 64-Bit Server VM JBR-11.0.8.10-944.34-jcef (build 11.0.8+10-b944.34, mixed mode)

❯  /Applications/IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/bin/java -jar ~/Library/Application\ Support/JetBrains/IntelliJIdea2020.2/plugins/plantuml4idea/lib/plantuml.1.2020.19.jar -t png ingest-global.puml
java.lang.IllegalArgumentException
	at net.sourceforge.plantuml.Dimension2DDouble.<init>(Dimension2DDouble.java:49)
	at net.sourceforge.plantuml.FileFormat.getJavaDimension(FileFormat.java:128)
	at net.sourceforge.plantuml.FileFormat.access$000(FileFormat.java:61)
	at net.sourceforge.plantuml.FileFormat$1.calculateDimension(FileFormat.java:118)
	at net.sourceforge.plantuml.creole.legacy.AtomText.calculateDimension(AtomText.java:199)
	at net.sourceforge.plantuml.creole.Sea.add(Sea.java:60)
	at net.sourceforge.plantuml.creole.SheetBlock1.initMap(SheetBlock1.java:117)
	at net.sourceforge.plantuml.creole.SheetBlock1.calculateDimension(SheetBlock1.java:159)
	at net.sourceforge.plantuml.creole.SheetBlock2.calculateDimension(SheetBlock2.java:90)
	at net.sourceforge.plantuml.graphic.USymbolRect$1.calculateDimension(USymbolRect.java:92)
	at net.sourceforge.plantuml.svek.image.EntityImageDescription.calculateDimension(EntityImageDescription.java:218)
	at net.sourceforge.plantuml.svek.Node.<init>(Node.java:98)
	at net.sourceforge.plantuml.svek.Bibliotekon.createNode(Bibliotekon.java:63)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntity(GeneralImageBuilder.java:547)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.printGroups(GeneralImageBuilder.java:606)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:411)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:112)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:77)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:654)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:173)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsCuca(PSystemUtils.java:233)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:89)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:160)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:538)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:422)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:389)
	at net.sourceforge.plantuml.Run.main(Run.java:198)

```

**Comment by matschaffer** [comment]
I plucked apart C4 a bit and found a more minimal reproduction case:

```
@startuml

skinparam rectangle<<boundary>> {
    StereotypeFontSize 0
}

rectangle blah <<boundary>>

@enduml
```

Seems like it's the `StereotypeFontSize` that leads to the issue.

**Comment by matschaffer** [comment]
I can't seem to find anywhere I can download a regular build of openjdk 11.0.8. The closest I could find was 11.0.2 which doesn't seem to exhibit the same problem as the one bundled with intellij.

```
❯ /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

❯ /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -jar plantuml.1.2020.19.jar -t png minimal.puml
```

**Comment by matschaffer** [comment]
I had to muck up the code a bit but I got Plantuml loaded in a debugger running from IntelliJ's java runtime and can see the `NaN` width

If I change that `StereotypeFontSize` to anything other than 0 it's a proper number, but you see it in the diagram (maybe as just 1 pixel line)

![plantuml_–_FileFormat_java](https://user-images.githubusercontent.com/690/98459931-d8e2cd80-21e2-11eb-82eb-54984aedebf6.png)

**Comment by matschaffer** [comment]
In oracle 11.0.9 I get `w=0.0`

So it seems like something having to do with how the IntelliJ JRE is interpreting that `0`.

Could maybe just wait till the next intellij release and see if that fixes it.

It's not a big issue, just caught me by surprise so thought I'd report it.

**Comment by krasa** [comment]
Report it here: https://forum.plantuml.net/

**Comment by krasa** [comment]
You can try a new JB JRE: https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-osx-x64/_latestVersion -> Files ->  jbrsdk

**Comment by krasa** [comment]
> Does the plugin run plantuml from the same JVM as intellij?

not only that, it runs in the same process

**Comment by krasa** [comment]
It seems not only JRE but also OS related.
![image](https://user-images.githubusercontent.com/1160875/98463307-9b6a4a00-21ba-11eb-966f-7f56d445c98f.png)
```
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
```

**Comment by matschaffer** [comment]
At this stage I'm thinking wait for the next jetbrains release. If it persists maybe open an plantuml issue to see if they can make it more resilient to a possible NaN when computing text width.

**Comment by krasa** [comment]
Seems fixed on the C4 end.
