### ISSUE TITLE
Plugin does not use configured dot.exe

### ISSUE THREAD

**Issue by DidierLoiseau** [esteinberg/plantuml4idea#280]
On our work laptops, we cannot run any application under our home folder. The administrators restricted permissions to only run programs under specific directories which they control.

It seems however that PlantUML now tries to use its embedded `dot.exe` instead of the one configured in the plugin settings:
```
java.io.IOException: Cannot run program "C:\Users\xxxxxx\AppData\Local\Temp\_graphviz\dot.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) 
	at java.base/java.lang.Runtime.exec(Runtime.java:592) 
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163) 
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123) 
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79) 
Caused by: java.io.IOException: CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at java.base/java.lang.ProcessImpl.create(Native Method) 
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478) 
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154) 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) 
	... 5 more 
java.io.IOException: Cannot run program "C:\Users\xxxxxx\AppData\Local\Temp\_graphviz\dot.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) 
	at java.base/java.lang.Runtime.exec(Runtime.java:592) 
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163) 
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123) 
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79) 
Caused by: java.io.IOException: CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at java.base/java.lang.ProcessImpl.create(Native Method) 
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478) 
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154) 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) 
	... 5 more 
java.lang.IllegalStateException: Timeout4 IO_EXCEPTION1 java.io.IOException: Cannot run program "C:\Users\xxxxxx\AppData\Local\Temp\_graphviz\dot.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at net.sourceforge.plantuml.svek.DotStringFactory.getSvg(DotStringFactory.java:309) 
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:463) 
	at net.sourceforge.plantuml.svek.GroupPngMakerState.getImage(GroupPngMakerState.java:165) 
	at net.sourceforge.plantuml.cucadiagram.dot.CucaDiagramSimplifierState.computeImage(CucaDiagramSimplifierState.java:116) 
	at net.sourceforge.plantuml.cucadiagram.dot.CucaDiagramSimplifierState.<init>(CucaDiagramSimplifierState.java:68) 
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:103) 
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:79) 
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:655) 
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:176) 
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140) 
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:160) 
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.generateImageItem(PlantUmlNormalRenderer.java:211) 
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.normalRendering(PlantUmlNormalRenderer.java:169) 
	at org.plantuml.idea.rendering.PlantUmlNormalRenderer.doRender(PlantUmlNormalRenderer.java:129) 
	at org.plantuml.idea.rendering.PlantUmlRendererUtil.render(PlantUmlRendererUtil.java:73) 
	at org.plantuml.idea.rendering.RenderCommand.run(RenderCommand.java:67) 
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:122) 
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20) 
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11) 
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270) 
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) 
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) 
	at java.base/java.security.AccessController.doPrivileged(Native Method) 
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) 
	at java.base/java.lang.Thread.run(Thread.java:834) 
Caused by: java.io.IOException: Cannot run program "C:\Users\xxxxxx\AppData\Local\Temp\_graphviz\dot.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) 
	at java.base/java.lang.Runtime.exec(Runtime.java:592) 
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163) 
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123) 
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79) 
Caused by: java.io.IOException: CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator 
	at java.base/java.lang.ProcessImpl.create(Native Method) 
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478) 
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154) 
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) 
	... 5 more 
```
I have checked that the `dot.exe` file is different (different file size).

What I have tried:
* Using the `GRAPHVIZ_DOT` environment variable (and the corresponding checkbox in the plugin settings)
* Using backslashes instead of the forward slashes (used by default when browsing to dot.exe in the UI)
* Upgrading to [the graphviz lite distribution from PlantUML](https://github.com/plantuml/graphviz-distributions) (version 2.44.1)

**Comment by krasa** [comment]
it seems hardcoded https://github.com/plantuml/plantuml/blob/9b708081fcec72ebe5fd4a10e66bc69988d2bb53/src/net/sourceforge/plantuml/windowsdot/WindowsDotArchive.java#L89

https://forum.plantuml.net/12468/plug-and-play-installation-for-windows?show=12472#c12472

**Comment by krasa** [comment]
imho downgrading the plugin/plantuml should help.

**Comment by arnaudroques** [comment]
Thanks for the report and sorry about that.
We are going to fix this one in next beta.
We'll post a message here when ready.

**Comment by DidierLoiseau** [comment]
Thanks @arnaudroques. If I am not wrong, the problem is just that [`GraphvizWindowsLite` overrides `searchDotExe()`](/plantuml/plantuml/blob/099843c8307b4fc97d88f99a8fab3ee5a4b9a20c/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizWindowsLite.java#L49), no?

Otherwise the default implementation would just use the `GRAPHVIZ_DOT` env/property, then the `PATH` env, before the fallback on the embedded exe.

Is there a github to track for this or it's just the above forum thread?

**Comment by arnaudroques** [comment]
> Thanks @arnaudroques. If I am not wrong, the problem is just that GraphvizWindowsLite overrides searchDotExe(), no?

Yes. All these need a proper refactor now :-)


> Is there a github to track for this or it's just the above forum thread?
Just the forum.
It should be fixed in last beta http://beta.plantuml.net/plantuml.jar

Tell us if it's not working for you !

**Comment by DidierLoiseau** [comment]
@krasa, is there a way to load that jar directly into the plugin?

**Comment by krasa** [comment]
@DidierLoiseau yes, just replace the jar in e.g. `C:\Users\x\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-4\203.5981.155.plugins\plantuml4idea\lib`

**Comment by DidierLoiseau** [comment]
Thanks, it's working for me with the beta 🙂

**Comment by krasa** [comment]
seems fixed in the new version
