### ISSUE TITLE
Argument for @NotNull parameter 'name' of …/FileUtil.sanitizeFileName must not be null

### ISSUE THREAD

**Issue by pokulo** [esteinberg/plantuml4idea#291]
I am using:

```
PyCharm 2020.3.3 (Professional Edition)
Build #PY-203.7148.72, built on January 27, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-133-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4460M
Cores: 4
Registry: debugger.watches.in.variables=false, debugger.valueTooltipAutoShowOnSelection=true
Non-Bundled Plugins: Org4Idea, com.intellij.ideolog, com.intellij.marketplace, com.intellij.plugins.eclipsekeymap, net.seesharpsoft.intellij.plugins.csv, uk.co.ben-gibson.remote.repository.mapper, PlantUML integration
Current Desktop: XFCE
```
and the `PlantUML integration` Plugin is Version `4.2.0`

Got the following StackTrace:

```java
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of com/intellij/openapi/util/io/FileUtil.sanitizeFileName must not be null
	at com.intellij.openapi.util.io.FileUtil.$$$reportNull$$$0(FileUtil.java)
	at com.intellij.openapi.util.io.FileUtil.sanitizeFileName(FileUtil.java)
	at org.plantuml.idea.action.save.AbstractSaveDiagramAction.sanitize(AbstractSaveDiagramAction.java:205)
	at org.plantuml.idea.action.save.AbstractSaveDiagramAction.getDefaultFileName(AbstractSaveDiagramAction.java:173)
	at org.plantuml.idea.action.save.AbstractSaveDiagramAction.actionPerformed(AbstractSaveDiagramAction.java:87)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:209)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:160)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:477)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90
```

Unfortunately I cannot recall how to reproduce, sorry. But I suspect, it happend with a newly created puml-File that was gone after switching from a branch back to `master` branch, where this file does not exist yet.

**Comment by krasa** [comment]
Fixed in https://plugins.jetbrains.com/plugin/7017-plantuml-integration/versions/stable/110587
