### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by pete-w** [esteinberg/plantuml4idea#313]
PlantUML v1.2021.7
IntelliJ IDEA 2021.1.2 build IU-211.7442.40 1/6/21

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator@6a4351c6 (class org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator) [Plugin: PlantUML integration]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:300)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:81)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:255)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:180)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:270)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:179)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at net.sourceforge.plantuml.tim.expression.ReversePolishInterpretor.<init>(ReversePolishInterpretor.java:106)
	at net.sourceforge.plantuml.tim.expression.TokenStack.getResult(TokenStack.java:245)
	at net.sourceforge.plantuml.tim.Eater.eatExpression(Eater.java:90)
	at net.sourceforge.plantuml.tim.EaterAffectation.analyze(EaterAffectation.java:72)
	at net.sourceforge.plantuml.tim.iterator.CodeIteratorAffectation.executeAffectation(CodeIteratorAffectation.java:95)
	at net.sourceforge.plantuml.tim.iterator.CodeIteratorAffectation.doAffectation(CodeIteratorAffectation.java:81)
	at net.sourceforge.plantuml.tim.iterator.CodeIteratorAffectation.peek(CodeIteratorAffectation.java:69)
	at net.sourceforge.plantuml.tim.TContext.executeLines(TContext.java:238)
	at net.sourceforge.plantuml.tim.TimLoader.load(TimLoader.java:66)
	at net.sourceforge.plantuml.BlockUml.<init>(BlockUml.java:124)
	at net.sourceforge.plantuml.BlockUmlBuilder.init(BlockUmlBuilder.java:123)
	at net.sourceforge.plantuml.BlockUmlBuilder.<init>(BlockUmlBuilder.java:74)
	at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:88)
	at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:80)
	at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:68)
	at net.sourceforge.plantuml.syntax.SyntaxChecker.checkSyntaxFair(SyntaxChecker.java:112)
	at org.plantuml.idea.adapter.Annotator.checkSyntax(Annotator.java:60)
	at org.plantuml.idea.adapter.Annotator.annotateSyntaxErrors(Annotator.java:32)
	at org.plantuml.idea.adapter.FacadeImpl.annotateSyntaxErrors(FacadeImpl.java:37)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:83)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.doAnnotate(PlantUmlExternalAnnotator.java:33)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:204)
	... 33 more
```

**Comment by krasa** [comment]
perhaps try V1.2021.8
