### ISSUE TITLE
Plant UML Plug-In 2.23.0 Failing In IntelliJ 2021.2

### ISSUE THREAD

**Issue by duffymo** [esteinberg/plantuml4idea#322]
I'm running Plant UML plug-in version 2.23.0 in IntelliJ 2021.2 build #IU-212.4746.92 on a MacBook Pro.  My JDK is OpenJDK 64-bit 11.0.11+9-b1504.13 x86_84.   I'm running graphviz dot version 2.49.0.

My PlantUML diagrams don't render.

The status indicated is green "cached".  

I see the following stack trace:

```
java.lang.NoSuchMethodError: 'java.awt.Image com.intellij.util.ui.ImageUtil.ensureHiDPI(java.awt.Image, com.intellij.util.ui.JBUI$ScaleContext)'
	at org.plantuml.idea.toolwindow.PlantUmlImageLabel.setDiagram(PlantUmlImageLabel.java:92)
	at org.plantuml.idea.toolwindow.PlantUmlImageLabel.setup(PlantUmlImageLabel.java:74)
	at org.plantuml.idea.toolwindow.PlantUmlImageLabel.<init>(PlantUmlImageLabel.java:55)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayImage(PlantUmlToolWindow.java:397)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.displayDiagram(PlantUmlToolWindow.java:367)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$MyRenderCommand.postRenderOnEDT(PlantUmlToolWindow.java:326)
	at org.plantuml.idea.rendering.RenderCommand$1.run(RenderCommand.java:79)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by krasa** [comment]
Why don't you update the plugin?

**Comment by duffymo** [comment]
Silly me - that sorted it.
