### ISSUE TITLE
Plugin stops working with latest PlantUml Snapshot, because DisplayPositionned was renamed

### ISSUE THREAD

**Issue by arittner** [esteinberg/plantuml4idea#337]
Hello!

In the last snapshots the class DisplayPositionned was renamed to DisplayPositioned. This means, the plugin will not work anymore with the next release. 

Details:

```

java.lang.NoSuchMethodError: 'net.sourceforge.plantuml.cucadiagram.DisplayPositionned net.sourceforge.plantuml.error.PSystemError.getTitle()'
	at org.plantuml.idea.adapter.rendering.Titles.initTitles(Titles.java:54)
	at org.plantuml.idea.adapter.rendering.Titles.<init>(Titles.java:26)
	at org.plantuml.idea.adapter.rendering.MyBlock.<init>(MyBlock.java:28)
	at org.plantuml.idea.adapter.rendering.DiagramFactory.create(DiagramFactory.java:60)
	at org.plantuml.idea.adapter.rendering.DiagramFactory.create(DiagramFactory.java:48)
	at org.plantuml.idea.adapter.rendering.PlantUmlNormalRenderer.doRender(PlantUmlNormalRenderer.java:20)
	at org.plantuml.idea.adapter.rendering.PlantUmlRendererUtil.render(PlantUmlRendererUtil.java:52)
	at org.plantuml.idea.adapter.FacadeImpl.render(FacadeImpl.java:83)
	at org.plantuml.idea.rendering.RenderCommand.render(RenderCommand.java:143)
	at org.plantuml.idea.rendering.LazyApplicationPoolExecutor$MyRunnable.run(LazyApplicationPoolExecutor.java:130)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

This line of code:

https://github.com/esteinberg/plantuml4idea/blob/master/adapter/src/org/plantuml/idea/adapter/rendering/Titles.java#L54

But I also faced an issue on line:

https://github.com/esteinberg/plantuml4idea/blob/master/adapter/src/org/plantuml/idea/adapter/rendering/Titles.java#L51

I guess this was a typo change to the new name DisplayPositioned (from DisplayPositionned).

See also discussion here: https://github.com/plantuml/plantuml/discussions/787

best regards, Aljoscha

**Comment by arnaudroques** [comment]
Sorry about this typo...
On PlantUML core library side, we propose [a temporary fix](https://github.com/plantuml/plantuml/pull/788) that will accept both `DisplayPositioned` and `DisplayPositionned`:

```
// This is ugly
public class DisplayPositioned implements DisplayPositionned {
...
```
Once this version will be released, you could use the new name `DisplayPositioned`.
Then, after a while, we will remove the deprecated `DisplayPositionned`.
What do you think about it?

**Comment by krasa** [comment]
sounds good
