### ISSUE TITLE
Support startdot and format dot

### ISSUE THREAD

**Issue by wenerme** [esteinberg/plantuml4idea#92]
Plantuml support `@startdot`, but plantuml4idea do not recongnize,no highlight and format.plantuml4idea said `No @startuml found`.

But plantuml4idea show the correct image on right side.

**Comment by krasa** [comment]
I don't even get an image
```
java.lang.IllegalStateException
	at net.sourceforge.plantuml.cucadiagram.dot.AbstractGraphviz.createFile3(Unknown Source)
	at net.sourceforge.plantuml.directdot.PSystemDot.exportDiagram(Unknown Source)
	at net.sourceforge.plantuml.SourceStringReader.generateImage(Unknown Source)
	at org.plantuml.idea.plantuml.PlantUml.render(PlantUml.java:169)
	at org.plantuml.idea.plantuml.PlantUml.render(PlantUml.java:80)
	at org.plantuml.idea.plantuml.PlantUml.render(PlantUml.java:59)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.renderWithBaseDir(PlantUmlToolWindow.java:169)
```

**Comment by wenerme** [comment]
![image](https://cloud.githubusercontent.com/assets/1777211/6679824/c10ca63c-cc88-11e4-8a91-58f65eb7e466.png)

**Comment by krasa** [comment]
http://plantuml.sourceforge.net/qa/?qa=3249/syntaxchecker%23checksyntax-does-not-recognize-%40startdot

**Comment by tohagan** [comment]
Any progress on this?   I'm sure many people would love to use GraphViz in IDEA.

**Comment by krasa** [comment]
Seems that plantuml devs missed my report...

**Comment by wenerme** [comment]
Actually I always use startuml for graphviz now. like [![](http://plantuml.com/plantuml/svg/IybCBqeio51mLwZcIbJGjLD8uge50000)](http://plantuml.com/plantuml/uml/IybCBqeio51mLwZcIbJGjLD8uge50000)

**Comment by krasa** [comment]
fixed

**Comment by tohagan** [comment]
Thanks!
