### ISSUE TITLE
Index out of Bound Exception (v1.6.1)

### ISSUE THREAD

**Issue by esteinberg** [esteinberg/plantuml4idea#94]
Wrong line: 254. Available lines count: 36
java.lang.IndexOutOfBoundsException: Wrong line: 254. Available lines count: 36
	at com.intellij.openapi.editor.ex.util.SegmentArray.getSegmentStart(SegmentArray.java:190)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:50)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:908)
	at org.plantuml.idea.lang.annotator.ErrorSourceAnnotation.annotate(ErrorSourceAnnotation.java:47)
	at org.plantuml.idea.lang.annotator.SourceAnnotationResult.annotate(SourceAnnotationResult.java:28)
	at org.plantuml.idea.lang.annotator.FileAnnotationResult.annotate(FileAnnotationResult.java:22)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.apply(PlantUmlExternalAnnotator.java:106)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.apply(PlantUmlExternalAnnotator.java:27)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectHighlighters(ExternalToolPass.java:166)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1$1.run(ExternalToolPass.java:130)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:124)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

java.lang.IndexOutOfBoundsException: Wrong line: 254. Available lines count: 36
	at com.intellij.openapi.editor.ex.util.SegmentArray.getSegmentStart(SegmentArray.java:190)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:50)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:908)
	at org.plantuml.idea.lang.annotator.ErrorSourceAnnotation.annotate(ErrorSourceAnnotation.java:47)
	at org.plantuml.idea.lang.annotator.SourceAnnotationResult.annotate(SourceAnnotationResult.java:28)
	at org.plantuml.idea.lang.annotator.FileAnnotationResult.annotate(FileAnnotationResult.java:22)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.apply(PlantUmlExternalAnnotator.java:106)
	at org.plantuml.idea.lang.annotator.PlantUmlExternalAnnotator.apply(PlantUmlExternalAnnotator.java:27)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectHighlighters(ExternalToolPass.java:166)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1$1.run(ExternalToolPass.java:130)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:124)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by krasa** [comment]
reproducible?

**Comment by krasa** [comment]
seems like rendering affects syntax checking, will report a bug.
![image](https://cloud.githubusercontent.com/assets/1160875/6680300/97107d28-cc55-11e4-86dd-89680c2c1de3.png)

**Comment by krasa** [comment]
http://plantuml.sourceforge.net/qa/?qa=3250/syntaxchecker%23checksyntax-is-not-thread-safe&show=3255#c3255

**Comment by krasa** [comment]
fixed, although no syntax validation after !include is possible for now
