### ISSUE TITLE
Random "Assertion Error"

### ISSUE THREAD

**Issue by jmdacruz** [esteinberg/plantuml4idea#98]
I'm getting *random* assertion errors when using the plugin (version 1.7.0). And by *random*, I mean that it I insert a few spaces or newlines on the document I can manage to get PlantUML to render the image, until the exception is thrown again later.

AFAICT, the error doesn't seem to be rooted in plugin itself but in the PlantUML code. Maybe a concurrency-related issue?

Stack trace follows below:

```
java.lang.AssertionError
	at net.sourceforge.plantuml.sequencediagram.InGroupableList.getMin(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.InGroupableList.getMinX(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.graphic.GroupingGraphicalElementHeader.drawInternalU(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.graphic.GraphicalElement.drawU(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.graphic.DrawableSet.drawPlaygroundU(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.graphic.DrawableSet.drawU22(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.graphic.SequenceDiagramFileMakerPuma2$1.drawU(Unknown Source)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(Unknown Source)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.graphic.SequenceDiagramFileMakerPuma2.createOne(Unknown Source)
	at net.sourceforge.plantuml.sequencediagram.SequenceDiagram.exportDiagramInternal(Unknown Source)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagram(Unknown Source)
	at net.sourceforge.plantuml.SourceStringReader.generateImage(Unknown Source)
	at org.plantuml.idea.plantuml.PlantUml.doRender(PlantUml.java:172)
	at org.plantuml.idea.plantuml.PlantUml.render(PlantUml.java:85)
	at org.plantuml.idea.plantuml.PlantUml.render(PlantUml.java:65)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.renderWithBaseDir(PlantUmlToolWindow.java:169)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow.access$500(PlantUmlToolWindow.java:36)
	at org.plantuml.idea.toolwindow.PlantUmlToolWindow$3$1.run(PlantUmlToolWindow.java:155)
	at org.plantuml.idea.util.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by krasa** [comment]
never seen that, you could try to update your plantuml.jar in ```C:\Users\xxx\.IntelliJIdea14\config\plugins\plantuml4idea\lib```  - from http://sourceforge.net/projects/plantuml/files/plantuml.jar/download

**Comment by jmdacruz** [comment]
I haven't tried manually upgrading the plantuml library, but I'm not able to reproduce the issue now (maybe the plugin got upgraded since I posted this issue?)

Running `java -jar plantuml.jar -v` on the library in the plugin gives me this:

```
0.000 - 245 Mo) 240 Mo - PlantUML Version 8021
(0.003 - 245 Mo) 240 Mo - GraphicsEnvironment.isHeadless() false
```

**Comment by krasa** [comment]
you have still the old version, the plugin was upgraded yesterday to 1.7.1 and it should return:
```
(0.000 - 245 Mo) 241 Mo - PlantUML Version 8025
(0.019 - 245 Mo) 241 Mo - GraphicsEnvironment.isHeadless() false
```

**Comment by jmdacruz** [comment]
Weird, I just updated to the latest version of the plugin, but now I'm getting a completely different error: I'm using [skinparam](http://plantuml.sourceforge.net/skinparam.html), and PlantUML tells me there is a syntax error, but this was working fine before.

Digging a bit deeper, I realized that when using version 8024 everything works fine, but when using version 8025 then the skinparam functionality doesn't work.

This is probably not an issue on your plugin anyways, so closing this issue for now.

**Comment by jmdacruz** [comment]
I actually detected what was broken between 8024 and 8025: My skinparam section had comments inside it (note the single quote on the last lines of the section). Removing the comments solves the issue, which makes this a backwards compatibility issue:

```
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    ActorBackgroundColor #BBBBBB
    LifeLineBorderColor Black
    LifeLineBackgroundColor #BBBBBB
    
    ParticipantBorderColor Black
    ParticipantBackgroundColor #AAAAAA

    BoxBorderColor Black

    'ParticipantFontName Impact
    'ParticipantFontSize 17
    'ParticipantFontColor #BBBBBB
    
    'ActorBackgroundColor aqua
    'ActorFontColor DeepSkyBlue
    'ActorFontSize 17
    'ActorFontName Aapex
}
```

I'm posting an issue into the PlantUML forum

**Comment by krasa** [comment]
:+1:
